# Created by: Kimo <kimor79@yahoo.com>
# $FreeBSD$

PORTNAME=	async_sinatra
PORTVERSION=	1.3.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sinatra plugin to provide async responses

LICENSE=	MIT

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}rack>=2.0.0:www/rubygem-rack \
		${RG_PKGNAMEPREFIX}sinatra>=1.4.8:www/rubygem-sinatra

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
