# Created by: Ryan Steinmetz <rpsfa@rit.edu>
# $FreeBSD$

PORTNAME=	dm-pager
PORTVERSION=	1.1.0
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	DataMapper Pagination

LICENSE=	MIT

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}dm-aggregates>=0.10.1:databases/rubygem-dm-aggregates \
		${RG_PKGNAMEPREFIX}dm-core>=0.10.1:databases/rubygem-dm-core

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
