# $FreeBSD$

PORTNAME=	vagrant-bhyve
PORTVERSION=	0.1.0
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Vagrant provider plugin to support bhyve

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}ruby_expect>=0:textproc/rubygem-ruby_expect

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
