# Created by: TERAMOTO Masahiro <markun@onohara.to>
# $FreeBSD$

PORTNAME=	rfeedfinder
PORTVERSION=	0.9.13
CATEGORIES=	www textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	markun@onohara.to
COMMENT=	Ruby library to find the feed

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}hpricot>=0.6:www/rubygem-hpricot \
		${RG_PKGNAMEPREFIX}htmlentities>=4.0.0:textproc/rubygem-htmlentities \
		${RG_PKGNAMEPREFIX}hoe>=1.7.0:devel/rubygem-hoe

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
