# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD$

PORTNAME=	jekyll-coffeescript
PORTVERSION=	1.1.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	CoffeeScript converter for Jekyll

LICENSE=	MIT

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}coffee-script>=2.2:devel/rubygem-coffee-script \
		${RG_PKGNAMEPREFIX}coffee-script-source>=1.11.1:devel/rubygem-coffee-script-source

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
