# $FreeBSD$

PORTNAME=	ruby-atmos-pure
PORTVERSION=	1.0.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Client library for EMC Atmos REST API

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}log4r>=1.1.9:sysutils/rubygem-log4r \
		${RG_PKGNAMEPREFIX}ruby-hmac>=0.4.0:security/rubygem-ruby-hmac

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
