# $FreeBSD$

PORTNAME=	omniauth-twitter
PORTVERSION=	1.4.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	OmniAuth strategy for Twitter

LICENSE=	MIT

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}omniauth-oauth>=1.1:net/rubygem-omniauth-oauth \
		${RG_PKGNAMEPREFIX}rack>=0:www/rubygem-rack

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
