# $FreeBSD$

PORTNAME=	astrolabe
PORTVERSION=	1.3.1
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Object-oriented AST extension for ${RG_PKGNAMEPREFIX}parser

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}parser>=2.2:devel/rubygem-parser

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
