# $FreeBSD$

PORTNAME=	best_in_place
PORTVERSION=	3.1.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-rails5

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	jQuery script to edit fields by clicking on them

LICENSE=	MIT

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}actionpack5>0:www/rubygem-actionpack5 \
		${RG_PKGNAMEPREFIX}railties5>0:www/rubygem-railties5

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
