# $FreeBSD$

PORTNAME=	dbd-mysql
PORTVERSION=	0.4.4
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	MySQL driver for DBI-for-Ruby

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}dbi>=0:databases/rubygem-dbi \
		${RG_PKGNAMEPREFIX}mysql>=0:databases/rubygem-mysql

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
