# Created by: Steven Kreuzer
# $FreeBSD$

PORTNAME=	rfacebook
PORTVERSION=	0.9.8
PORTREVISION=	1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby interface to the Facebook API

LICENSE=	BSD4CLAUSE

RUN_DEPENDS=	${RG_PKGNAMEPREFIX}hpricot>=0.6.0:www/rubygem-hpricot \
		${RG_PKGNAMEPREFIX}mocha>=0.5.3:devel/rubygem-mocha

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
